/**
 * Field is anatomy, not wiring.
 *
 * `Field`, `FieldLabel`, `FieldDescription` and `FieldError` give a form
 * control its structure and layout. The accessibility relationships —
 * `htmlFor`, `id`, `aria-describedby`, `aria-invalid` — are the call site's,
 * written explicitly, which is what this file shows working. Nothing here is
 * generated by the components, and the documentation says so.
 */

import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";

import { Field, FieldDescription, FieldError, FieldLabel } from "../../src/components/field";
import { Input } from "../../src/components/input";
import { Label } from "../../src/components/label";

describe("Field", () => {
  it("carries explicit wiring from the call site through to the control", () => {
    render(
      <Field data-invalid>
        <FieldLabel htmlFor="name">Name</FieldLabel>
        <Input id="name" aria-describedby="name-hint name-error" aria-invalid />
        <FieldDescription id="name-hint">Shown on your profile.</FieldDescription>
        <FieldError id="name-error">Required</FieldError>
      </Field>,
    );

    const input = screen.getByLabelText("Name");
    expect(input.getAttribute("aria-invalid")).toBe("true");
    const described = (input.getAttribute("aria-describedby") ?? "")
      .split(" ")
      .map((id) => document.getElementById(id)?.textContent);
    expect(described).toEqual(["Shown on your profile.", "Required"]);

    const group = screen.getByRole("group");
    expect(group.getAttribute("data-slot")).toBe("field");
    expect(group.hasAttribute("data-invalid")).toBe(true);
  });

  it("adds no relationship the call site did not write", () => {
    render(
      <Field>
        <FieldLabel>Name</FieldLabel>
        <Input aria-label="Name" />
        <FieldDescription>Shown on your profile.</FieldDescription>
      </Field>,
    );
    const input = screen.getByRole("textbox", { name: "Name" });
    expect(input.hasAttribute("aria-describedby")).toBe(false);
    expect(input.hasAttribute("aria-invalid")).toBe(false);
  });

  it("associates a label with its control by id", () => {
    render(
      <>
        <Label htmlFor="tag">Tag</Label>
        <Input id="tag" defaultValue="v1" />
      </>,
    );
    expect(screen.getByLabelText("Tag")).toHaveProperty("value", "v1");
  });
});

describe("FieldError", () => {
  it("announces its content as an alert", () => {
    render(<FieldError>must not be blank</FieldError>);
    expect(screen.getByRole("alert").textContent).toBe("must not be blank");
  });

  it("lists distinct messages once each, and a single message as plain text", () => {
    const { unmount } = render(
      <FieldError
        errors={[{ message: "too short" }, { message: "too short" }, { message: "no digits" }]}
      />,
    );
    expect(screen.getAllByRole("listitem").map((li) => li.textContent)).toEqual([
      "too short",
      "no digits",
    ]);
    unmount();

    render(<FieldError errors={[{ message: "too short" }]} />);
    expect(screen.queryByRole("listitem")).toBeNull();
    expect(screen.getByRole("alert").textContent).toBe("too short");
  });

  it("renders nothing without a message", () => {
    render(<FieldError errors={[]} />);
    expect(screen.queryByRole("alert")).toBeNull();
  });
});
